LANG_DICT = {
    "en": "english",
    "ar": "arabic",
    "cs": "czech",
    "de": "german",
    "es": "spanish",
    "fi": "finnish",
    "fr": "french",
    "gl": "galician",
    "hi": "hindi",
    "id": "indonesian",
    "is": "icelandic",
    "it": "italian",
    "ja": "japanese",
    "ko": "korean",
    "pl": "polish",
    "pt": "portuguese",
    "ru": "russian",
    "sv": "swedish",
    "th": "thai",
    "tr": "turkish",
    "zh": "chinese",
}
